- util.c
Certificate passed via command line with a size larger than the expected
maximum filename size fail the stat syscall with ENAMETOOLONG rather
than ENOENT, which causes decode_file() to consider it as a filename
rather than inline.
> Fix unexpected behavior when using a long certificate in command line.

- extensions.h
A bad copy-paste included a semi-colon at the end of the #define making
it impossible to use in some cases.
> Fix bad extension ID defines.

- PROTOCOL.extensions
- certificates.c
- hiba-ca.sh
- testdata/regression-test.sh
- util.c
Support for multiple HIBA grants attached to one certificate.
This pull request also includes: 
- testing for multiple identities (this must result in access denied)
- debug log rewording
> Hiba multiple grants

- Makefile.am
- configure.ac
This allows for more complete checks and better compatibility with
various setups.
> Move remaining compilation options to configure.ac

- PROTOCOL.grl
This CL removes `uint16 size` previously specified in the grant revocation bitmap section and documents the algorithm for calculating bitmap size and checking grant revocation for a certificate serial and grant index.
> docs: update GRL wire format and check algorithm

- certificates.c
- util.c
The issue with `sshsk_sign` can happen if projects wants to include
libhiba.so. Include sshsk_sign in libhiba.so directly for external
projects to depend on instead of having them work around it individually
Signed-off-by: Willy Tu <wltu@google.com>
> Expose util.c for external project

- certificates.c
https://github.com/openssh/openssh-portable/pull/358 tries to properly fix the missing `sshsk_sign` symbol in OpenSSH.
Once that pull request is merged, HIBA might fail to build against newer versions of OpenSSH since the symbol will now be duplicated (depending on compilers). As we can't easily declare a clean cut-off, making the symbol weak will allow for a smoother transition.
> Make the dummy sshsk_sign symbol weak.

- revocations.c
Commit c7a3d77c0b8c153d463398606a8d57569186a0c3 in OpenSSH sources made the struct sshbuf private, which broke our introspection into the sshbuf offset. This was only needed for augmenting the debug data and not critical at all, so it can safely be removed.
Fixes #29
> Fix broken revocations.c compilation.

- CA.md
- README.md
How to actually create grants/identities and sign certificates with these probably not is immediately obvious, so an example is probably useful for those wanting to go beyond the local setup shell script.
> Adding a CA usage example to README.md

- checks.c
- testdata/regression-test.sh
The authorizatyion logic relies on an internal grant extension for merging the result of similar keys (OR semantic). Since this extension was allocated but not initialized, the merging logic failed.
This results in repeated keys to be handled as last one wins.
> Fix missing extension initialization.

- certificates.c
- certificates.h
- checks.c
- checks.h
- configure.ac
- errors.h
- extensions.c
- extensions.h
- hiba-chk.c
- hiba-gen.c
- hiba-grl.c
- hiba.h
- revocations.c
- revocations.h
- util.c
- util.h
This fixes some duplicate symbol compilation errors on darwin toolchains caused by inlined libc functions.
This change does:
- convert all // comments to /**/ comments
- replace explicit `inline` with `__inline__`
- add `-ansi` to CFLAGS
- fix missing definitions for u_char and u_int used by OpenSSH
> Switch to using -ansi for compilation.

- INSTALL.md
- hiba-gen.c
- testdata/regression-test.sh
- testdata/test-utils.sh
The 3 HIBA binaries (hiba-gen, hiba-chk and hiba-grl) can now run under valgrind (for instance) to provide better diagnostics about memory management in libhiba.
This also fix one minor leak on the hiba-gen command line tool detected using this mechanism.
> Add support for static code checking while running regression tests.

- PROTOCOL.authorizations
- PROTOCOL.extensions
- checks.c
- extensions.c
- extensions.h
- testdata/regression-test.sh
This negative matching constraints are expressed as: "not a key which value is X".
This is implemented using the `!` as a key modifier. The documentation is updated to reflect this new capability in the HIBA protocol.
A new set of regression tests is also provided to confirm the behavior of negative matching constraints.
> Add support for negative matching constraints.

- PROTOCOL.extensions
With the addition of negative constraint matching, and in order to avoid unintended authiorizations, the extension format version was increased to 2 for all grants actually using negative matching, but can stay at 1 for everything else (grant with only positive matching and identities).
> Update documentation to explain the current extension format version.

- PROTOCOL.extensions
Previous commit (72b8445d702e71a2b30e72832f80b98de43d36d7) explained the high level idea but creates confusion between version and min_version fields.
This commit clarifies both fields expected values.
> Update documentation to clarify min_version versus version requirement.

- PROTOCOL.authorizations
All of the negative constraints must not match for access to be granted is equivalent to a single negative constraint matching will result in denied access. The former phrasing better reflects the AND semantic.
> Clarify documentation about AND semantic for negative constraint matching

- configure.ac
- revocations.c
- enable clang compilation to run with ubsan
- fix ubsan warning
- update minor version to 2 so that we can add tag v1.2
> Fix ubsan finding

- testdata/test-utils.sh
The test utils script also updates the PATH to ensure regression tests run against the latest binaries rather than the preinstalled ones.
> test-utils: copy built files to the test temporary folder.

- checks.c
Allowing authentication using identity doesn't cause much harm, but can cause confusion when user sets up their OpenSSH config wrong and pass the invert command line parameters. With this check, authorization will fail fast.
> Verify the incoming authentication has a type grant.

- configure.ac
This leads to _FORTIFY_SOURCE check sometimes only triggering a warning when redefined, but later on, this warning being promoted to error when checking for another unrelated dependency.
> Fix missing -Werror in some configure tests.

- revocations.c
During compile on macOS the default unused variable checking appears to be strict and found this.
```
revocations.c:259:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
u_int64_t i = 0;
^
```
> Remove unused variable in revocations.c

- PROTOCOL.grl
Previously PROTOCOL.grl omitted details about the uint64 which indicates the number of fixed size entries in the serials section of the binary format grant revocation list.  The serial section size is required to differentiate between the final entry in the serials section and the revoked grants bitmask section.
> Document GRL certificate serial section size

- extensions.c
- testdata/regression-test.sh
The option constraint in a HIBA grant can be used for restricting users to a given command similar to authorized_keys or authorized_users.
The command can contain quotes by escaping them with a backslash, which was not implemented in the sanity check until now.
> Improve support for quotes in 'option' constraint.

- certificates.c
- checks.c
- extensions.c
- revocations.c
We will hit -Werror=calloc-transposed-args when we start moving to gcc-14. Migrate to the new API to make sure no build fails.
> fix build against upcoming gcc-14

- extensions.c
sshbuf_b64tod expects a NULL terminated string, but base64 encoded extensions may not be since they are extracted from an SSH buffer which manages size as metadata directly.
> extensions: fix heap-buffer-overflow in hibaext_decode.
